CREATE TABLE IF NOT EXISTS `dungeon_runs` (
  `run_id` varchar(64) NOT NULL,
  `guild_id` varchar(32) NOT NULL,
  `channel_id` varchar(32) NOT NULL,
  `message_id` varchar(32) NOT NULL,
  `message_url` varchar(255) DEFAULT NULL,
  `party_leader_id` varchar(32) NOT NULL,
  `party_leader_name` varchar(100) DEFAULT NULL,
  `dungeon_key` varchar(50) NOT NULL,
  `start_time_ms` bigint(20) unsigned NOT NULL,
  `registration_end_time_ms` bigint(20) unsigned DEFAULT NULL,
  `description` text DEFAULT NULL,
  `notification_mode` varchar(32) DEFAULT NULL,
  `multiple_assignments` tinyint(1) NOT NULL DEFAULT 0,
  `assignments` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`assignments`)),
  `member_names` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`member_names`)),
  `join_order` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`join_order`)),
  `status` enum('open','closed_full','closed_deadline','closed_missing_message') NOT NULL DEFAULT 'open',
  `close_reason` varchar(32) DEFAULT NULL,
  `closed_at_ms` bigint(20) unsigned DEFAULT NULL,
  `created_at_ms` bigint(20) unsigned NOT NULL,
  `reminder_counter` int(10) unsigned NOT NULL DEFAULT 0,
  `reminders_enabled` tinyint(1) NOT NULL DEFAULT 1,
  `reminders_stop_at_ms` bigint(20) unsigned DEFAULT NULL,
  `storage_origin` enum('mysql','json_fallback','json_only') NOT NULL DEFAULT 'mysql',
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`run_id`),
  KEY `idx_dungeon_runs_status` (`status`),
  KEY `idx_dungeon_runs_guild_id` (`guild_id`),
  KEY `idx_dungeon_runs_channel_id` (`channel_id`),
  KEY `idx_dungeon_runs_registration_end` (`registration_end_time_ms`),
  KEY `idx_dungeon_runs_updated_at` (`updated_at`),
  KEY `idx_dungeon_runs_storage_origin` (`storage_origin`),
  CONSTRAINT `chk_dungeon_runs_notification_mode`
    CHECK (`notification_mode` IS NULL OR `notification_mode` IN ('dm','channel','channel_hidden'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
