CREATE TABLE IF NOT EXISTS `guild_applications` (
  `post_id` varchar(32) NOT NULL,
  `topic_id` varchar(32) NOT NULL,
  `topic_url` varchar(512) NOT NULL,
  `post_url` varchar(512) NOT NULL,
  `page_number` int unsigned NOT NULL DEFAULT 1,
  `forum_user_id` varchar(32) DEFAULT NULL,
  `forum_username` varchar(128) DEFAULT NULL,
  `forum_profile_url` varchar(512) DEFAULT NULL,
  `forum_profile_slug` varchar(128) DEFAULT NULL,
  `posted_at` datetime(6) DEFAULT NULL,
  `observed_at` datetime(6) NOT NULL,
  `content_hash` char(64) NOT NULL,
  `raw_body_text` longtext NOT NULL,
  `image_urls` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`image_urls`)),
  `classification` enum('application','non_application','ignored_author','duplicate_user') NOT NULL,
  `classification_confidence` decimal(5,4) NOT NULL DEFAULT 0.0000,
  `parser_reasons` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`parser_reasons`)),
  `ocr_output` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (`ocr_output` IS NULL OR json_valid(`ocr_output`)),
  `ign` varchar(128) DEFAULT NULL,
  `ign_source` varchar(32) DEFAULT NULL,
  `ign_confidence` decimal(5,4) NOT NULL DEFAULT 0.0000,
  `age` varchar(32) DEFAULT NULL,
  `country` varchar(128) DEFAULT NULL,
  `interests` text DEFAULT NULL,
  `extra_information` text DEFAULT NULL,
  `is_baseline` tinyint(1) NOT NULL DEFAULT 0,
  `notification_status` varchar(32) NOT NULL DEFAULT 'not_required',
  `officer_message_id` varchar(32) DEFAULT NULL,
  `officer_message_url` varchar(255) DEFAULT NULL,
  `poll_message_id` varchar(32) DEFAULT NULL,
  `poll_message_url` varchar(255) DEFAULT NULL,
  `poll_created_at` datetime(6) DEFAULT NULL,
  `vote_reminder_12h_checked_at` datetime(6) DEFAULT NULL,
  `vote_reminder_12h_message_id` varchar(32) DEFAULT NULL,
  `vote_reminder_18h_checked_at` datetime(6) DEFAULT NULL,
  `vote_reminder_18h_message_id` varchar(32) DEFAULT NULL,
  `last_error` text DEFAULT NULL,
  `notified_at` datetime(6) DEFAULT NULL,
  `storage_origin` enum('mysql','json_fallback','json_only') NOT NULL DEFAULT 'mysql',
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`post_id`),
  KEY `idx_guild_applications_topic_page` (`topic_id`,`page_number`),
  KEY `idx_guild_applications_forum_user` (`forum_user_id`,`classification`,`posted_at`),
  KEY `idx_guild_applications_forum_name` (`forum_username`,`classification`,`posted_at`),
  KEY `idx_guild_applications_classification` (`classification`,`posted_at`),
  KEY `idx_guild_applications_notification` (`notification_status`,`is_baseline`),
  KEY `idx_guild_applications_vote_reminders` (`poll_created_at`,`vote_reminder_12h_checked_at`,`vote_reminder_18h_checked_at`),
  KEY `idx_guild_applications_observed_at` (`observed_at`),
  KEY `idx_guild_applications_storage_origin` (`storage_origin`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
